SCREEN_W, SCREEN_H = 800, 600
SCREEN_SIZE = (SCREEN_W, SCREEN_H)
GROUND_HEIGHT = SCREEN_H - 62
BG_MULTI = 2.68
BLOOD_MULTI = 1.0
BRICK_MULTI = 2.9
ENEMY_MULTI = 2.5
ENEMY_SPEED = 1
# PLAYER_MULTI = 2.69
PLAYER_MULTI = 1.5
TREASURE_MULTI = 2.5
FIRE_CONTROL = 60.0
FIRE_CONTROL_HAND = 0.0
FONT = 'Ark Pixel.ttf'

GRAVITY = 1.0
ANTI_GRAVITY = 0.3

